### ISSUE TITLE
Salam khoya ana mn les fans dyalk brit rir ngolik b li atscan fiha chi mochkil f ip range 

### ISSUE THREAD

**Issue by megylon** [AlisamTechnology/ATSCAN#10]
matalan akhoya fach kandir had command : atscan -t 45.115.36.227 -l 10 --sites 
katkhdem mezyana ohya asslan tool m9awda hhh <3 
[!] 7 Unique Result(s) Found!
[i] Results saved in z1.txt!
[!] [00:57:35] SCAN FINISHED!!
walakin fach kandir range : atscan -t 45.115.36.227-45.115.36.247 -l 10 --sites 
makatkhdemch okat3tini 
[!] No Results Found! 
ye3ni fach kandir ip bo7do tatkhdem walakin kandir range makatkhdemch 
osme7 lya khoya ola7fdek lina <3

**Comment by AlisamTechnology** [comment]
daba nraja3ha. merci

**Comment by megylon** [comment]
Akhoya welat chi 7aja daroria bach nkhdem man9edch nbe3ed 3liha <3

**Comment by AlisamTechnology** [comment]
you are welcome khouya
