### ISSUE TITLE
History and stay in "use" chain after run finishes 

### ISSUE THREAD

**Issue by bxck75** [AlisamTechnology/ATSCAN#13]
Hi! I have been testing/using interactive mode for some days now and it works fine so far!
Are u going to make a history function in a later stadium?
And when a run finishes the prompt alway jumps back to atscan> instead of staying in the chosen use chain.
Also trying to mod the script in my fork of your tool 

Gtz BXCK

**Comment by AlisamTechnology** [comment]
chain now is ok after run or help or config
