### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Mehran** [AlisamTechnology/ATSCAN#16]
im not Perl familiar , 

`Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/atscan//atscan.pl line 7.`

**Comment by SCREAM2017** [comment]
How to fix this
