### ISSUE TITLE
atscan -h error

### ISSUE THREAD

**Issue by testerfr810** [AlisamTechnology/ATSCAN#19]
hi, when i type
atscan -h i have that ???

syntax error at /usr/share/atscan/inc/help.pl line 40, near "."
Compilation failed in require at /usr/share/atscan/inc/conf/main.pl line 97.
Compilation failed in require at /usr/share/atscan/inc/index.pl line 11.
Compilation failed in require at /usr/share/atscan/inc/includes.pl line 60.
Compilation failed in require at /usr/share/atscan//atscan.pl line 105.

an idea ???

ty

**Comment by AlisamTechnology** [comment]
RESOLVED!! thanks.
