### ISSUE TITLE
يوجد مشكله في تخمين البسورد 

### ISSUE THREAD

**Issue by ameryasseramer** [AlisamTechnology/ATSCAN#2]
[ ]-----------------------------------
 [23:27:25] [Target 7/26]              
 TARGET: http://www.dermahaircenter.com
 CMS:    Wordpress!                    
 USER:   admin                         
 PASS:   admin%d                       
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   1234%d                        
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   123%d                         
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   password%d                    
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   user%d                        
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   admin123%d                    
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   admin1%d                      
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   ADMIN1%d                      
 SCAN:   Not Vulnerable!               
 USER:   admin                         
 PASS:   ADMIN                         
 SCAN:   Not Vulnerable!

**Comment by AlisamTechnology** [comment]
فقط في كتابة ظهور  كلمات السر و ليس في الفحص على اي انا عالجت المشكل جرب الان

**Comment by ameryasseramer** [comment]
تسلم يا غالي اريدك ان تعمل معي اريد ان اتكلم معك بمقابل جيد جدا

**Comment by ameryasseramer** [comment]
ارجو ان يكون جميع الاصدرات موجوده
