### ISSUE TITLE
مشكله

### ISSUE THREAD

**Issue by SCREAM2017** [AlisamTechnology/ATSCAN#20]
scream@ADWAA:/mnt/c/users/ad/desktop/Tools/ATSCAN-master$ atscan --bugtraq joomla

         /\ ___ /\
        (  o   o  )             https://www.fb.com/Alisam.Technology
        \  >#<  /
         /       \            _  _____ ____   ____    _    _   _
        /         \   ^      / \|_   _/ ___| / ___|  / \  | \ | |
       |           | ||     / _ \ | | \___ \| |     / _ \ |  \| |
        \          /-//    / ___ \| |  ___) | |___ / ___ \| |\  |
         ///  ///--       /_/   \_\_| |____/ \____/_/   \_\_| \_| V 14.0.3
________________________________________________________________________________

  Disclaimer: Using ATSCAN to Attack targets without prior mutual consent is
  illegal! It is your own responsibility to obey laws! Alisam Technology is
  not linked to any kind of loss or misuse or damage caused by this program!
________________________________________________________________________________
--------------------------------------------------------------------------------
[!] Please wait...
[!] No results found!
[19:57:32] EXPLORING [joomla] ISSUES...
[i] 0 Results found!
[!] [19:57:36] SCAN FINISHED!!
scream@ADWAA:/mnt/c/users/ad/desktop/Tools/ATSCAN-master$

**Comment by AlisamTechnology** [comment]
Thanks for your notice.
the issue is solved.a
To update use: atscan --repair
