### ISSUE TITLE
not working..

### ISSUE THREAD

**Issue by nilotpalbiswas** [AlisamTechnology/ATSCAN#24]
sir.. after update its giving error..
root@kali:~# atscan -h

          . \\\|||/// 
         / \ ========
         \ /| O   O | 
          #  \` _ '/            -oO Alisam Technology Oo-
         (#)   | |   
          #\/( * * )\          _  _____ ____   ____    _    _   _  
          #\/(==*==)/         / \|_   _/ ___| / ___|  / \  | \ | |
          #   || ||          / _ \ | | \___ \| |     / _ \ |  \| |
         .#---'| |`----.    / ___ \| |  ___) | |___ / ___ \| |\  |
         '#---'   `----'   /_/   \_\_| |____/ \____/_/   \_\_| \_| V 16.0.6
________________________________________________________________________________

Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/i386-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base) at /usr/share/atscan/inc/search/process.pl line 93.
BEGIN failed--compilation aborted at /usr/share/atscan/inc/search/process.pl line 93.
Compilation failed in require at /usr/share/atscan/inc/includes.pl line 62.
Compilation failed in require at /usr/share/atscan//atscan.pl line 86.

**Comment by AlisamTechnology** [comment]
Thanks for reporting bug! this happend because you need to install JSON perl module. 
i will change it in next version today to ask for json only when needed.
