### ISSUE TITLE
interactive mode error

### ISSUE THREAD

**Issue by CyberTheReape** [AlisamTechnology/ATSCAN#25]
hello. i am get this error with help command after switching to interactive mode

atscan --interactive

help

--------------------------------------------------------------------------------------------------------------------------------
[::] HELP
Undefined subroutine &Interactive::ltak called at /usr/share/atscan/inc/lib/lib/Interactive.pm line 384, <STDIN> line 1.

**Comment by AlisamTechnology** [comment]
thanks for reporting. 
u can update it is ok now.

**Comment by CyberTheReape** [comment]
problem not solved ...same problem continues

**Comment by AlisamTechnology** [comment]
Sorry is my mistake . i did not save changes please report for bugs.

**Comment by CyberTheReape** [comment]
İt is work now... thnks
