### ISSUE TITLE
Can't locate JSON.pm in @INC (you may need to install the JSON module)

### ISSUE THREAD

**Issue by derainbow** [AlisamTechnology/ATSCAN#26]
please help, i got an error 
when try to install this.

here screenshot of an error
[https://i.imgur.com/zeFAshd.png](https://i.imgur.com/zeFAshd.png)

**Comment by AlisamTechnology** [comment]
because you need to install JSON perl package this is used for shodan search. but i solved it you can install  now it will not ask for json module.
