### ISSUE TITLE
Apikey

### ISSUE THREAD

**Issue by eudomoniacc** [AlisamTechnology/ATSCAN#27]
I tried the solution of

atscan --config 
set apikey with my cse id but whenever i want to search for a dork it gives me an error for internet conecction.

Can you please add info for how to add apikey for google custom search, cse and cx apis? And also for shodan please as permanantely. 

At older versions of atscan, we didnt have to add an api key and everything was working flawlessly.
Thank you.

**Comment by AlisamTechnology** [comment]
Apikey is needed for googleapis and shodan search!!
cx is your googleapis search ID!!
THIS ONLY REQUIRED WHEN USING SHODAN OR GOOGLEAPIS !!
YOU DONT NEED APIKEYS OR CX FOR GOOGLE ASK BING ... SEARCH !!

EXAMPLE HOW TO USE:
atscan -d holidays -l 1  -m googleapis --apikey GSDSSGSGHSGHS --cx XXXXXXXX
atscan -d windows -l 1 --shodan --apikey HGSKJSDJSHSHS

SET OPTIONS IN CONFIG PANEL:
atscan --config
set apikey HSJKSKSKLSJSHSHSHS
set cx XXXXXXXXXXX (this for googleapis)
set motor shodan
exit

atscan -d windows -l 1  will search windows in shodan
NOTE: CONNECTION ERROR IF ANY IS INCORRECT!!
