### ISSUE TITLE
error commad --email

### ISSUE THREAD

**Issue by rudiana587** [AlisamTechnology/ATSCAN#29]
i have command
# atscan --dork list.txt --level 10 --email --save link.txt
error
Undefined subroutine &Subs: :eMails called at /usr/share/atscan/ /atscan.pl line 185.

**Comment by AlisamTechnology** [comment]
thanks for advising i will cheeck the tool.

**Comment by AlisamTechnology** [comment]
solved

**Comment by rudiana587** [comment]
Thanks very much, i really like this tool.
You're d best
