### ISSUE TITLE
Using on termux

### ISSUE THREAD

**Issue by Mik39907** [AlisamTechnology/ATSCAN#30]
When I try to run it it gives me the logo but also an error 
Undefined subroutine &Print::basename called at /data/data/com.termux/files/home/ATSCAN/inc/lib/lib/Print.pm line 107.
Can someone help me?

**Comment by Mik39907** [comment]
BTW I'm using it as portable my device can't install it

**Comment by Mik39907** [comment]
BTW I'm using it as portable my device can't install it

**Comment by AlisamTechnology** [comment]
solved!! update tool
