### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by Mik39907** [AlisamTechnology/ATSCAN#31]
Geolocate IP doesn't work and also some others on Termux so not sure if I will be using it but if you want to try to fix them check the Proxy ones work for me it didn't and also no error
Command:
perl ./atscan.pl -t ?.?.?.? --geoloc
Error:
Undefined subroutine &Subs::geoSrver called at ./atscan.pl line 432.

**Comment by AlisamTechnology** [comment]
solved

**Comment by Mik39907** [comment]
No it stops after saying the Agent it just stays there I've waited around 5min and it didn't move

**Comment by AlisamTechnology** [comment]
is the server problem is down not the tool !!! will loock for new one when have time.
