### ISSUE TITLE
Can't locate Term/ReadKey.pm in @INC

### ISSUE THREAD

**Issue by M0dred** [AlisamTechnology/ATSCAN#32]
Can't locate Term/ReadKey.pm in @INC (you may need to install the Term::ReadKey module) (@INC contains: /usr/share/atscan/inc/lib/lib /usr/share/atscan/inc/lib /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/share/atscan/inc/lib/lib/Login.pm line 6.
BEGIN failed--compilation aborted at /usr/share/atscan/inc/lib/lib/Login.pm line 6.
Compilation failed in require at /usr/share/atscan//atscan.pl line 122.
BEGIN failed--compilation aborted at /usr/share/atscan//atscan.pl line 122.

**Comment by AlisamTechnology** [comment]
Because u need to install  ReadKey module!!
https : // ubuntu.pkgs.org/16.04/ubuntu-universe-amd64/libterm-readkey-perl_2.33-1build1_amd64.deb. html
