### ISSUE TITLE
cant  locate term

### ISSUE THREAD

**Issue by CezarFSociety** [AlisamTechnology/ATSCAN#38]
it wont run on Xubuntu 19.10 
Input: sudo atscan
Output: Can't locate Term/ReadKey.pm in @INC (you may need to install the Term::ReadKey module) (@INC contains: /Desktop/inc/lib/lib /Desktop/inc/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /Desktop/inc/lib/lib/Login.pm line 6.
BEGIN failed--compilation aborted at /Desktop/inc/lib/lib/Login.pm line 6.
Compilation failed in require at /Desktop/atscan.pl line 122.
BEGIN failed--compilation aborted at /Desktop/atscan.pl line 122.
------------------------------------------
2nd try.
Click on the atscan app
output:Can't locate Term/ReadKey.pm in @INC (you may need to install the Term::ReadKey module) (@INC contains: /Desktop/inc/lib/lib /Desktop/inc/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /Desktop/inc/lib/lib/Login.pm line 6.
BEGIN failed--compilation aborted at /Desktop/inc/lib/lib/Login.pm line 6.
Compilation failed in require at /Desktop/atscan.pl line 122.
BEGIN failed--compilation aborted at /Desktop/atscan.pl line 122.

**Comment by AlisamTechnology** [comment]
you have to install Term::ReadKey module.
