### ISSUE TITLE
--exp, --expHost, --payload seems not working for me

### ISSUE THREAD

**Issue by allexstorm** [AlisamTechnology/ATSCAN#39]
For example I try to use this simple command:
atscan -d "product.php?product_id=" -l 1 --exp "product.php?product_id=rang(1-20)" -m google
I get in output just Target and IP for every dork result, --exp... part not done. I tried also --expHost, --host --exp, nothing works for me. Ofcourse I tried other --exp commands too, many from youtube examples, also example from this repo: atscan -d "/index.php?id=" --expHost "/index.php?id=rang(1-9)" --sql -l 1. Please advice.

**Comment by AlisamTechnology** [comment]
update the tool. atscan --update
