### ISSUE TITLE
save file

### ISSUE THREAD

**Issue by Simobelaidi** [AlisamTechnology/ATSCAN#4]
there is a problem in --save it save nothing

**Comment by AlisamTechnology** [comment]
can u give me the full commande line u used?

**Comment by Simobelaidi** [comment]
./atscan.pl -t ***.2.80.*** --level 200 --site --save
great tool btw thanks it help alot and save time :D

**Comment by AlisamTechnology** [comment]
--save filename.txt

**Comment by Simobelaidi** [comment]
work fine thanks
