### ISSUE TITLE
googleapis erro

### ISSUE THREAD

**Issue by qrt2** [AlisamTechnology/ATSCAN#40]
***atscan_ -d inurl:wp-cotent -m googleapis -l 20 -s lis0.txt***
![Screenshot_20200524-160544](https://user-images.githubusercontent.com/65868516/82762677-c31a5100-9dd8-11ea-8935-0244754854be.png)

_malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/atscan/inc/lib/Subs.pm line 227._

**Comment by AlisamTechnology** [comment]
thanks to report issue! this error because you are getting no results !! make an update and report if ok i did some changes but not tested yet.

**Comment by qrt2** [comment]
json error has been fixed! thanks but now another problem it doesn't bring results even if i change dork ![Screenshot_20200524-173257](https://user-images.githubusercontent.com/65868516/82764545-ea2b4f80-9de5-11ea-91a3-997b416bbaa5.png)
the other search engines work normally!
 ![Screenshot_20200524-173351](https://user-images.githubusercontent.com/65868516/82764667-dcc29500-9de6-11ea-950c-04a431b5029b.png)
 ![Screenshot_20200524-173319](https://user-images.githubusercontent.com/65868516/82764676-ef3cce80-9de6-11ea-9f1a-c17a3681e6e0.png)

googleapis google cache does not bring results
and yes my api and cx are configured
  so much that atscan checks before doing the search!
 ![IMG_20200524_174712_043](https://user-images.githubusercontent.com/65868516/82764688-0c719d00-9de7-11ea-84de-2db8fa876482.jpg)
