### ISSUE TITLE
Strings validation seems not working properly

### ISSUE THREAD

**Issue by allexstorm** [AlisamTechnology/ATSCAN#42]
Next command used:

sudo atscan -t http://site.com/page -v /home/ATSCAN/include.txt

[!] 1 Unique Result(s) Found!

 ==============================================================================
 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 ==============================================================================
 TARGET    [1/1] http://site.com/page
 IP        ip here
 AGENT     Mozilla/5.0 (Mozilla/5.0 (compatible; Konqueror/3.5; en-US; SunOS) Safari
 STATUS    200
 SERVER    Apache
 CMS       Wordpress 
 PLUGINS   [!] Plugins detected!
             - theme => theme here
 SCAN      http://site.com/page
 ==============================================================================
 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 ==============================================================================
--------------------------------------------------------------------------------
[!] 1 Unique Result(s) Found!
[01:06:30] SCAN FINISHED!

I watched videos, there should be VALID string after CMS like:
VALID [word1][word2][word3]

Please advice.

**Comment by AlisamTechnology** [comment]
It is working but seems that u have seen an old video..!! the version 17.0.0 is not showing strings..!! but i did it today. you can do an update. thanks for reporting
