### ISSUE TITLE
issue to get different TARGET from external command

### ISSUE THREAD

**Issue by dragonxtek** [AlisamTechnology/ATSCAN#43]
When I search and I use: --command "curl -sv --TARGET", the first target is fixed to all results.
For every result, the command always use the first result target

![Selection_999(359)](https://user-images.githubusercontent.com/10552658/88120463-ecfdb300-cb90-11ea-87cc-8d2106f34454.png)
As you can see, the second result, use the same first url.
How can I fix this issue?

**Comment by AlisamTechnology** [comment]
THIS IS WORKING CORRECTLY
