### ISSUE TITLE
issue to select all motor engines

### ISSUE THREAD

**Issue by dragonxtek** [AlisamTechnology/ATSCAN#44]
When I select the command -m all, atscan can't detect it

![Selection_999(360)](https://user-images.githubusercontent.com/10552658/88120614-5c73a280-cb91-11ea-9d91-cd87edb56db9.png)

**Comment by AlisamTechnology** [comment]
I will resolve it this week end. thanks for reporting bugs

**Comment by AlisamTechnology** [comment]
SOLVED
