### ISSUE TITLE
how to run an external command on every search hit

### ISSUE THREAD

**Issue by max037** [AlisamTechnology/ATSCAN#45]
Hello,

as you described in issue: **issue to get different TARGET from external command #43**, the --TARGET value is fix for one related host. I also tried the --command option with the the mode --HOST. But i also get the the same behavior, that every external command on different search hits is execute with the first finding from the search engine.

Let me please know, how to manage your program, that i can run an external command on every search hit. If it is not possible yet, this would be a very essentially feature.

thanks!

**Comment by AlisamTechnology** [comment]
Thanks for reporting. normaly it runs the command on every target!!  I will check it once I have time. thanks again

**Comment by AlisamTechnology** [comment]
is done!! --command or -c "your command"
