### ISSUE TITLE
[Solved] Error requiring level when already stated

### ISSUE THREAD

**Issue by lav13enrose** [AlisamTechnology/ATSCAN#47]
Got a problem 

Executed : 
`atscan --dork list.txt --level 2`

Got Error : 

> [!] You have to set number of results pages. Ex: --level 3

thank you

**Comment by lav13enrose** [comment]
fixed by manually set it on `atscan --config``

**Comment by AlisamTechnology** [comment]
thanks for reporting. it is solved now
