### ISSUE TITLE
Shodan scraping issue

### ISSUE THREAD

**Issue by kfedorek** [AlisamTechnology/ATSCAN#49]
trying to run a shodan scrape. Other scrape is working with search engines. Except google returns no results its probably due to tor proxy and being blocked. So i run on linux
sudo atscan --shodan --api apikeyhere --level 2 --dork dorkhere and it initializes and api connects OK and it shows the dork used and level but then upon returning results i get this error for each line or page. What is causing this? Thanks!

Use of uninitialized value $v_shoRes in pattern match (m//) at /usr/share/atscan/inc/lib/Shodan.pm line 75.
Use of uninitialized value $v_shoRes in pattern match (m//) at /usr/share/atscan/inc/lib/Shodan.pm line 75.

**Comment by AlisamTechnology** [comment]
thanks for reporting the error is because the search has no results. i made some changes quickly if still giving problem report to me thanks.
