### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by jordy4shizzle** [AlisamTechnology/ATSCAN#5]
I receive this error on execution: 

`Undefined subroutine &main::headerSearch called at ./atscan.pl line 1814` 

when I type: `./atscan.pl --dork inurl:index.php?id= --level 40 --xss`

Strangely it worked well yesterday but I had to re-install ATSCAN because I ran a live version of Kali. I also tried to run it from my server but receive the same error. Is it patched or something? I find it really weird. Any help would be very appreciated!

**Comment by AlisamTechnology** [comment]
thanks i fix it.
