### ISSUE TITLE
Can't locate HTTP/Cookies.pm in @INC

### ISSUE THREAD

**Issue by AlexC-ux** [AlisamTechnology/ATSCAN#52]
### Error message when starting an application

> Can't locate HTTP/Cookies.pm in @INC (you may need to install the HTTP::Cookies module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/atscan//atscan.pl line 45.
> BEGIN failed--compilation aborted at /usr/share/atscan//atscan.pl line 45.

**Comment by AlexC-ux** [comment]
`cpan HTTP::Cookies` did not give any result.

**Comment by AlexC-ux** [comment]
I use WSL and I had to run the program with administrator privileges to get everything working correctly.

I used `cpan {modulename}` to install multiple modules. Thank you all for your attention.
![image](https://user-images.githubusercontent.com/55258939/144722705-d84d479a-7b64-467c-9927-41313a82103a.png)

**Comment by AlisamTechnology** [comment]
install HTTP cookies module
sudo apt install libhttp-cookiejar-perl
