### ISSUE TITLE
Bugtraq error + NO target url shown

### ISSUE THREAD

**Issue by xMunduSCodEx** [AlisamTechnology/ATSCAN#53]
I tried to uninstall and reinstall whole package but didnt work.
I could never run the tool due to the following errors:
1st)
Use of uninitialized value in concatenation (.) or string at /usr/share/atscan/inc/lib/Bugtraq.pm line 142.
2nd) NO target url shown

Example use: atscan --bugtraq --dork "inurl:index.php?id=" --level 1
Output as image attached
![atscan](https://user-images.githubusercontent.com/97990659/163465816-5ca9928a-e6e7-4e82-9052-0412c9faed17.png)

**Comment by AlisamTechnology** [comment]
dork in bugtraq is not like google dork!!!! u must search by products example: windows safari ecommerce... or vendors
