### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Kdigital01** [AlisamTechnology/ATSCAN#57]
[root@185 ATSCAN]# atscan
Can't locate Digest/MD5.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/atscan//atscan.pl line 41.
BEGIN failed--compilation aborted at /usr/share/atscan//atscan.pl line 41.

any solution?

**Comment by AlisamTechnology** [comment]
install MD5 module
