### ISSUE TITLE
Feature: Bash autocompletion

### ISSUE THREAD

**Issue by vdun** [AlisamTechnology/ATSCAN#6]

**Comment by vdun** [comment]
added / commit / ignored ?

**Comment by AlisamTechnology** [comment]
No bro! i never ignore suggestions!! i'am rebuilding the script and i will try to make autocomplete. im still learning bro.. thanks for all

**Comment by vdun** [comment]
Then please keep the issue Issue/Feature open till someone has time implement it.

**Comment by AlisamTechnology** [comment]
ok. Note: i autocompletion in perl require chage getopt module and i try to suse standar perl modules because a lot of users fails to update or install  modules!

**Comment by vdun** [comment]
it should be a simple bash script.
here is a nice tutorial: https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1

**Comment by AlisamTechnology** [comment]
thanks man!

**Comment by AlisamTechnology** [comment]
Added! thanks for guiding me.
