### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SOTUS** [AlisamTechnology/ATSCAN#9]
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
\C no longer supported in regex; marked by <-- HERE in m/(\ <-- HERE C)/ at /usr/share/perl5/URI/Escape.pm line 205.
Compilation failed in require at /usr/share/atscan//atscan.pl line 7.
BEGIN failed--compilation aborted at /usr/share/atscan//atscan.pl line 7.

**Comment by AlisamTechnology** [comment]
YOU HAVE TO INSTALL URI::Escape module!!!
go to terminal and type:
1) perl -MCPAN -e shell
2) install URI::Escape

**Comment by keyunlocker12** [comment]
Mine is still having issues an not installing on my termux on android. What do I do next?

**Comment by AlisamTechnology** [comment]
ATSCAN is made to use in linux or windows!! for android some people did it maybe by googling in youtube u will get some help.

**Comment by keyunlocker12** [comment]
OK thanks.
